
// This file has been generated by the GUI designer. Do not modify.
namespace MGME4Linux
{
	public partial class MainWindowMGME
	{
		private global::Gtk.UIManager UIManager;

		private global::Gtk.Action FileAction;

		private global::Gtk.Action ExitAction;

		private global::Gtk.Action FileAction1;

		private global::Gtk.Action LoadAnswersAction;

		private global::Gtk.Action SaveAnswersAction;

		private global::Gtk.Action LoadCharacterListAction;

		private global::Gtk.Action SaveCharacterListAction;

		private global::Gtk.Action LoadThreadListAction;

		private global::Gtk.Action SaveThreadListAction;

		private global::Gtk.Action Action;

		private global::Gtk.Action ExitAction1;

		private global::Gtk.VBox vbox1;

		private global::Gtk.MenuBar menubar2;

		private global::Gtk.HBox hbox1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label labelFateQuestion;

		private global::Gtk.Entry entryFateQuestion;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Label labelChaosFactor;

		private global::Gtk.HBox hbox6;

		private global::Gtk.ComboBox comboboxChaosFactor;

		private global::Gtk.Button buttonChaosFactorRoll;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label labelOdds;

		private global::Gtk.ComboBox comboboxOdds;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Label labelMeaningTables;

		private global::Gtk.HBox hbox9;

		private global::Gtk.ComboBox comboBoxMeaningTablesFiles1;

		private global::Gtk.ComboBox comboBoxMeaningTablesFiles2;

		private global::Gtk.Button buttonGenerateMeaning;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Button buttonAsk;

		private global::Gtk.CheckButton checkbuttonAddAnswer;

		private global::Gtk.Button buttonRandomEvent;

		private global::Gtk.Button buttonRollPercentile;

		private global::Gtk.Button buttonLogClear;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView textviewLog;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Label labelCharacterList;

		private global::Gtk.Entry entryCharacter;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView listCharacters;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Button buttonCharacterListClear;

		private global::Gtk.Button buttonCharacterListRoll;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Label labelThreadList;

		private global::Gtk.Entry entryThread;

		private global::Gtk.ScrolledWindow GtkScrolledWindow2;

		private global::Gtk.TreeView listThreads;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Button buttonThreadListClear;

		private global::Gtk.Button buttonThreadListRoll;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget MGME4Linux.MainWindowMGME
			this.UIManager = new global::Gtk.UIManager();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup("Default");
			this.FileAction = new global::Gtk.Action("FileAction", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString("File");
			w1.Add(this.FileAction, null);
			this.ExitAction = new global::Gtk.Action("ExitAction", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
			this.ExitAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
			w1.Add(this.ExitAction, null);
			this.FileAction1 = new global::Gtk.Action("FileAction1", global::Mono.Unix.Catalog.GetString("File"), null, null);
			this.FileAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("&File");
			w1.Add(this.FileAction1, null);
			this.LoadAnswersAction = new global::Gtk.Action("LoadAnswersAction", global::Mono.Unix.Catalog.GetString("Load Answers"), null, null);
			this.LoadAnswersAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Load Answers");
			w1.Add(this.LoadAnswersAction, null);
			this.SaveAnswersAction = new global::Gtk.Action("SaveAnswersAction", global::Mono.Unix.Catalog.GetString("Save Answers"), null, null);
			this.SaveAnswersAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save Answers");
			w1.Add(this.SaveAnswersAction, null);
			this.LoadCharacterListAction = new global::Gtk.Action("LoadCharacterListAction", global::Mono.Unix.Catalog.GetString("Load Character List"), null, null);
			this.LoadCharacterListAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Load Character List");
			w1.Add(this.LoadCharacterListAction, null);
			this.SaveCharacterListAction = new global::Gtk.Action("SaveCharacterListAction", global::Mono.Unix.Catalog.GetString("Save Character List"), null, null);
			this.SaveCharacterListAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save Character List");
			w1.Add(this.SaveCharacterListAction, null);
			this.LoadThreadListAction = new global::Gtk.Action("LoadThreadListAction", global::Mono.Unix.Catalog.GetString("Load Thread List"), null, null);
			this.LoadThreadListAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Load Thread List");
			w1.Add(this.LoadThreadListAction, null);
			this.SaveThreadListAction = new global::Gtk.Action("SaveThreadListAction", global::Mono.Unix.Catalog.GetString("Save Thread List"), null, null);
			this.SaveThreadListAction.ShortLabel = global::Mono.Unix.Catalog.GetString("Save Thread List");
			w1.Add(this.SaveThreadListAction, null);
			this.Action = new global::Gtk.Action("Action", global::Mono.Unix.Catalog.GetString("-"), null, null);
			this.Action.ShortLabel = global::Mono.Unix.Catalog.GetString("-");
			w1.Add(this.Action, null);
			this.ExitAction1 = new global::Gtk.Action("ExitAction1", global::Mono.Unix.Catalog.GetString("Exit"), null, null);
			this.ExitAction1.ShortLabel = global::Mono.Unix.Catalog.GetString("Exit");
			w1.Add(this.ExitAction1, null);
			this.UIManager.InsertActionGroup(w1, 0);
			this.AddAccelGroup(this.UIManager.AccelGroup);
			this.Name = "MGME4Linux.MainWindowMGME";
			this.Title = global::Mono.Unix.Catalog.GetString("MGME");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child MGME4Linux.MainWindowMGME.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString(@"<ui><menubar name='menubar2'><menu name='FileAction1' action='FileAction1'><menuitem name='LoadAnswersAction' action='LoadAnswersAction'/><menuitem name='SaveAnswersAction' action='SaveAnswersAction'/><menuitem name='LoadCharacterListAction' action='LoadCharacterListAction'/><menuitem name='SaveCharacterListAction' action='SaveCharacterListAction'/><menuitem name='LoadThreadListAction' action='LoadThreadListAction'/><menuitem name='SaveThreadListAction' action='SaveThreadListAction'/><menuitem name='Action' action='Action'/><menuitem name='ExitAction1' action='ExitAction1'/></menu></menubar></ui>");
			this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget("/menubar2")));
			this.menubar2.Name = "menubar2";
			this.vbox1.Add(this.menubar2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.menubar2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.labelFateQuestion = new global::Gtk.Label();
			this.labelFateQuestion.Name = "labelFateQuestion";
			this.labelFateQuestion.Xalign = 0F;
			this.labelFateQuestion.LabelProp = global::Mono.Unix.Catalog.GetString("Fate Question:");
			this.vbox2.Add(this.labelFateQuestion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.labelFateQuestion]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.entryFateQuestion = new global::Gtk.Entry();
			this.entryFateQuestion.CanFocus = true;
			this.entryFateQuestion.Name = "entryFateQuestion";
			this.entryFateQuestion.IsEditable = true;
			this.entryFateQuestion.InvisibleChar = '•';
			this.vbox2.Add(this.entryFateQuestion);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.entryFateQuestion]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.labelChaosFactor = new global::Gtk.Label();
			this.labelChaosFactor.Name = "labelChaosFactor";
			this.labelChaosFactor.LabelProp = global::Mono.Unix.Catalog.GetString("Chaos Factor:");
			this.vbox6.Add(this.labelChaosFactor);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.labelChaosFactor]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.comboboxChaosFactor = global::Gtk.ComboBox.NewText();
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("4"));
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("6"));
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("7"));
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("8"));
			this.comboboxChaosFactor.AppendText(global::Mono.Unix.Catalog.GetString("9"));
			this.comboboxChaosFactor.Name = "comboboxChaosFactor";
			this.hbox6.Add(this.comboboxChaosFactor);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.comboboxChaosFactor]));
			w6.Position = 0;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonChaosFactorRoll = new global::Gtk.Button();
			this.buttonChaosFactorRoll.CanFocus = true;
			this.buttonChaosFactorRoll.Name = "buttonChaosFactorRoll";
			this.buttonChaosFactorRoll.UseUnderline = true;
			this.buttonChaosFactorRoll.Label = global::Mono.Unix.Catalog.GetString("Roll");
			this.hbox6.Add(this.buttonChaosFactorRoll);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.buttonChaosFactorRoll]));
			w7.Position = 1;
			this.vbox6.Add(this.hbox6);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.hbox6]));
			w8.Position = 1;
			w8.Expand = false;
			this.hbox5.Add(this.vbox6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox6]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.labelOdds = new global::Gtk.Label();
			this.labelOdds.Name = "labelOdds";
			this.labelOdds.LabelProp = global::Mono.Unix.Catalog.GetString("Odds:");
			this.vbox7.Add(this.labelOdds);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.labelOdds]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.comboboxOdds = global::Gtk.ComboBox.NewText();
			this.comboboxOdds.Name = "comboboxOdds";
			this.vbox7.Add(this.comboboxOdds);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.comboboxOdds]));
			w11.Position = 1;
			this.hbox5.Add(this.vbox7);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox7]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.labelMeaningTables = new global::Gtk.Label();
			this.labelMeaningTables.Name = "labelMeaningTables";
			this.labelMeaningTables.Xalign = 0F;
			this.labelMeaningTables.LabelProp = global::Mono.Unix.Catalog.GetString("Meaning Tables:");
			this.vbox8.Add(this.labelMeaningTables);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.labelMeaningTables]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.comboBoxMeaningTablesFiles1 = global::Gtk.ComboBox.NewText();
			this.comboBoxMeaningTablesFiles1.Name = "comboBoxMeaningTablesFiles1";
			this.hbox9.Add(this.comboBoxMeaningTablesFiles1);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.comboBoxMeaningTablesFiles1]));
			w14.Position = 0;
			// Container child hbox9.Gtk.Box+BoxChild
			this.comboBoxMeaningTablesFiles2 = global::Gtk.ComboBox.NewText();
			this.comboBoxMeaningTablesFiles2.Name = "comboBoxMeaningTablesFiles2";
			this.hbox9.Add(this.comboBoxMeaningTablesFiles2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.comboBoxMeaningTablesFiles2]));
			w15.Position = 1;
			// Container child hbox9.Gtk.Box+BoxChild
			this.buttonGenerateMeaning = new global::Gtk.Button();
			this.buttonGenerateMeaning.CanFocus = true;
			this.buttonGenerateMeaning.Name = "buttonGenerateMeaning";
			this.buttonGenerateMeaning.UseUnderline = true;
			this.buttonGenerateMeaning.Label = global::Mono.Unix.Catalog.GetString("Generate Meaning");
			this.hbox9.Add(this.buttonGenerateMeaning);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.buttonGenerateMeaning]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox8.Add(this.hbox9);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.hbox9]));
			w17.Position = 1;
			w17.Expand = false;
			w17.Fill = false;
			this.hbox5.Add(this.vbox8);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox8]));
			w18.Position = 2;
			this.vbox2.Add(this.hbox5);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox5]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonAsk = new global::Gtk.Button();
			this.buttonAsk.CanFocus = true;
			this.buttonAsk.Name = "buttonAsk";
			this.buttonAsk.UseUnderline = true;
			this.buttonAsk.Label = global::Mono.Unix.Catalog.GetString("Ask");
			this.hbox8.Add(this.buttonAsk);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonAsk]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.checkbuttonAddAnswer = new global::Gtk.CheckButton();
			this.checkbuttonAddAnswer.CanFocus = true;
			this.checkbuttonAddAnswer.Name = "checkbuttonAddAnswer";
			this.checkbuttonAddAnswer.Label = global::Mono.Unix.Catalog.GetString("Add Answer");
			this.checkbuttonAddAnswer.Active = true;
			this.checkbuttonAddAnswer.DrawIndicator = true;
			this.checkbuttonAddAnswer.UseUnderline = true;
			this.hbox8.Add(this.checkbuttonAddAnswer);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.checkbuttonAddAnswer]));
			w21.Position = 1;
			w21.Expand = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonRandomEvent = new global::Gtk.Button();
			this.buttonRandomEvent.CanFocus = true;
			this.buttonRandomEvent.Name = "buttonRandomEvent";
			this.buttonRandomEvent.UseUnderline = true;
			this.buttonRandomEvent.Label = global::Mono.Unix.Catalog.GetString("Random Event");
			this.hbox8.Add(this.buttonRandomEvent);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonRandomEvent]));
			w22.Position = 2;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonRollPercentile = new global::Gtk.Button();
			this.buttonRollPercentile.CanFocus = true;
			this.buttonRollPercentile.Name = "buttonRollPercentile";
			this.buttonRollPercentile.UseUnderline = true;
			this.buttonRollPercentile.Label = global::Mono.Unix.Catalog.GetString("Roll Percentile");
			this.hbox8.Add(this.buttonRollPercentile);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonRollPercentile]));
			w23.Position = 3;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.buttonLogClear = new global::Gtk.Button();
			this.buttonLogClear.CanFocus = true;
			this.buttonLogClear.Name = "buttonLogClear";
			this.buttonLogClear.UseUnderline = true;
			this.buttonLogClear.Label = global::Mono.Unix.Catalog.GetString("Clear");
			this.hbox8.Add(this.buttonLogClear);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.buttonLogClear]));
			w24.PackType = ((global::Gtk.PackType)(1));
			w24.Position = 4;
			w24.Expand = false;
			w24.Fill = false;
			this.vbox2.Add(this.hbox8);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox8]));
			w25.Position = 3;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.textviewLog = new global::Gtk.TextView();
			this.textviewLog.CanFocus = true;
			this.textviewLog.Name = "textviewLog";
			this.GtkScrolledWindow.Add(this.textviewLog);
			this.vbox2.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.GtkScrolledWindow]));
			w27.Position = 4;
			this.hbox1.Add(this.vbox2);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w28.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.labelCharacterList = new global::Gtk.Label();
			this.labelCharacterList.Name = "labelCharacterList";
			this.labelCharacterList.Xalign = 0F;
			this.labelCharacterList.LabelProp = global::Mono.Unix.Catalog.GetString("Character List:");
			this.vbox3.Add(this.labelCharacterList);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.labelCharacterList]));
			w29.Position = 0;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.entryCharacter = new global::Gtk.Entry();
			this.entryCharacter.CanFocus = true;
			this.entryCharacter.Name = "entryCharacter";
			this.entryCharacter.IsEditable = true;
			this.entryCharacter.InvisibleChar = '•';
			this.vbox3.Add(this.entryCharacter);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.entryCharacter]));
			w30.Position = 1;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.listCharacters = new global::Gtk.TreeView();
			this.listCharacters.CanFocus = true;
			this.listCharacters.Name = "listCharacters";
			this.GtkScrolledWindow1.Add(this.listCharacters);
			this.vbox3.Add(this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.GtkScrolledWindow1]));
			w32.Position = 2;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonCharacterListClear = new global::Gtk.Button();
			this.buttonCharacterListClear.CanFocus = true;
			this.buttonCharacterListClear.Name = "buttonCharacterListClear";
			this.buttonCharacterListClear.UseUnderline = true;
			this.buttonCharacterListClear.Label = global::Mono.Unix.Catalog.GetString("Clear");
			this.hbox3.Add(this.buttonCharacterListClear);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonCharacterListClear]));
			w33.Position = 0;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.buttonCharacterListRoll = new global::Gtk.Button();
			this.buttonCharacterListRoll.CanFocus = true;
			this.buttonCharacterListRoll.Name = "buttonCharacterListRoll";
			this.buttonCharacterListRoll.UseUnderline = true;
			this.buttonCharacterListRoll.Label = global::Mono.Unix.Catalog.GetString("Roll");
			this.hbox3.Add(this.buttonCharacterListRoll);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.buttonCharacterListRoll]));
			w34.PackType = ((global::Gtk.PackType)(1));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox3.Add(this.hbox3);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox3]));
			w35.Position = 3;
			w35.Expand = false;
			w35.Fill = false;
			this.hbox1.Add(this.vbox3);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox3]));
			w36.Position = 1;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.labelThreadList = new global::Gtk.Label();
			this.labelThreadList.Name = "labelThreadList";
			this.labelThreadList.Xalign = 0F;
			this.labelThreadList.LabelProp = global::Mono.Unix.Catalog.GetString("Thread List:");
			this.vbox4.Add(this.labelThreadList);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.labelThreadList]));
			w37.Position = 0;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.entryThread = new global::Gtk.Entry();
			this.entryThread.CanFocus = true;
			this.entryThread.Name = "entryThread";
			this.entryThread.IsEditable = true;
			this.entryThread.InvisibleChar = '●';
			this.vbox4.Add(this.entryThread);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.entryThread]));
			w38.Position = 1;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.listThreads = new global::Gtk.TreeView();
			this.listThreads.CanFocus = true;
			this.listThreads.Name = "listThreads";
			this.GtkScrolledWindow2.Add(this.listThreads);
			this.vbox4.Add(this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.GtkScrolledWindow2]));
			w40.Position = 2;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonThreadListClear = new global::Gtk.Button();
			this.buttonThreadListClear.CanFocus = true;
			this.buttonThreadListClear.Name = "buttonThreadListClear";
			this.buttonThreadListClear.UseUnderline = true;
			this.buttonThreadListClear.Label = global::Mono.Unix.Catalog.GetString("Clear");
			this.hbox4.Add(this.buttonThreadListClear);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonThreadListClear]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.buttonThreadListRoll = new global::Gtk.Button();
			this.buttonThreadListRoll.CanFocus = true;
			this.buttonThreadListRoll.Name = "buttonThreadListRoll";
			this.buttonThreadListRoll.UseUnderline = true;
			this.buttonThreadListRoll.Label = global::Mono.Unix.Catalog.GetString("Roll");
			this.hbox4.Add(this.buttonThreadListRoll);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.buttonThreadListRoll]));
			w42.PackType = ((global::Gtk.PackType)(1));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.vbox4.Add(this.hbox4);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.hbox4]));
			w43.Position = 3;
			w43.Expand = false;
			w43.Fill = false;
			this.hbox1.Add(this.vbox4);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox4]));
			w44.PackType = ((global::Gtk.PackType)(1));
			w44.Position = 2;
			w44.Expand = false;
			w44.Fill = false;
			this.vbox1.Add(this.hbox1);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w45.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 803;
			this.DefaultHeight = 300;
			this.Show();
			this.LoadAnswersAction.Activated += new global::System.EventHandler(this.LoadAnswersActivated);
			this.SaveAnswersAction.Activated += new global::System.EventHandler(this.SaveAnswersActivated);
			this.LoadCharacterListAction.Activated += new global::System.EventHandler(this.LoadCharactersActivated);
			this.SaveCharacterListAction.Activated += new global::System.EventHandler(this.SaveCharactersActivated);
			this.LoadThreadListAction.Activated += new global::System.EventHandler(this.LoadThreadsActivated);
			this.SaveThreadListAction.Activated += new global::System.EventHandler(this.SaveThreadsActivated);
			this.ExitAction1.Activated += new global::System.EventHandler(this.ExitAppActivated);
			this.buttonChaosFactorRoll.Clicked += new global::System.EventHandler(this.RollClicked);
			this.buttonGenerateMeaning.Clicked += new global::System.EventHandler(this.GenerateMeaningClicked);
			this.buttonAsk.Clicked += new global::System.EventHandler(this.doAskFateQuestion);
			this.buttonRandomEvent.Clicked += new global::System.EventHandler(this.RandomEventClicked);
			this.buttonRollPercentile.Clicked += new global::System.EventHandler(this.RollPercentileClicked);
			this.buttonLogClear.Clicked += new global::System.EventHandler(this.AnswersClearClicked);
			this.entryCharacter.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.CharacterKeyReleaseEvent);
			this.listCharacters.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.CharacterListKeyRelease);
			this.buttonCharacterListClear.Clicked += new global::System.EventHandler(this.CharacterClearClicked);
			this.buttonCharacterListRoll.Clicked += new global::System.EventHandler(this.CharacterRollClicked);
			this.entryThread.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.ThreadKeyReleaseEvent);
			this.listThreads.KeyReleaseEvent += new global::Gtk.KeyReleaseEventHandler(this.ThreadListKeyRelease);
			this.buttonThreadListClear.Clicked += new global::System.EventHandler(this.ThreadClearClicked);
			this.buttonThreadListRoll.Clicked += new global::System.EventHandler(this.ThreadRollClicked);
		}
	}
}
